### ISSUE TITLE
Project layout creates code duplication

### ISSUE THREAD

**Issue by bpglaser** [TheRealGangsir/WikiBot#3]
At current, the layout of the project makes it difficult to create new commands or refactor old. One possible solution would be to move all commands into their own submodule. Then, when making a new command, the command is reexported via said submodule.

**Comment by bpglaser** [comment]
Likewise, by moving all "extern crate"'s into lib.rs you eliminate the need to use "extern crate" in each file that uses the imported crate.

**Comment by Sublimelime** [comment]
Merged.
